<?php 
echo '[
    {
        "start": "2024-05-27T07:00",
        "end": "2024-05-27T07:20",
        "title": "최종현2(현우)",
        "reservation_id": 4284,
        "user_name": "최종현2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 502,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "07",
        "start_mi": "00",
        "end_hh": "07",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T08:00",
        "end": "2024-05-27T08:20",
        "title": "박동희(현우)",
        "reservation_id": 4285,
        "user_name": "박동희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 618,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "08",
        "start_mi": "00",
        "end_hh": "08",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T09:20",
        "end": "2024-05-27T09:40",
        "title": "김혜진(현우)",
        "reservation_id": 4286,
        "user_name": "김혜진(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 578,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-27",
        "start_hh": "09",
        "start_mi": "20",
        "end_hh": "09",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T10:20",
        "end": "2024-05-27T10:40",
        "title": "이상일2(현우)",
        "reservation_id": 4287,
        "user_name": "이상일2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 667,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "10",
        "start_mi": "20",
        "end_hh": "10",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T15:00",
        "end": "2024-05-27T15:20",
        "title": "이대건(현우)",
        "reservation_id": 4288,
        "user_name": "이대건(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 609,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "15",
        "start_mi": "00",
        "end_hh": "15",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T15:20",
        "end": "2024-05-27T15:40",
        "title": "김경린(현우)",
        "reservation_id": 4289,
        "user_name": "김경린(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 604,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "15",
        "start_mi": "20",
        "end_hh": "15",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T15:40",
        "end": "2024-05-27T16:00",
        "title": "권석숭2(현우)",
        "reservation_id": 4290,
        "user_name": "권석숭2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 639,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-27",
        "start_hh": "15",
        "start_mi": "40",
        "end_hh": "16",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T17:00",
        "end": "2024-05-27T17:20",
        "title": "이정원(현우)",
        "reservation_id": 4291,
        "user_name": "이정원(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 640,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "17",
        "start_mi": "00",
        "end_hh": "17",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T18:00",
        "end": "2024-05-27T18:20",
        "title": "오동민(현우)",
        "reservation_id": 4292,
        "user_name": "오동민(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 641,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "18",
        "start_mi": "00",
        "end_hh": "18",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T18:20",
        "end": "2024-05-27T18:40",
        "title": "정순용(현우)",
        "reservation_id": 4293,
        "user_name": "정순용(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 631,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "18",
        "start_mi": "20",
        "end_hh": "18",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T19:00",
        "end": "2024-05-27T19:20",
        "title": "전세현2(현우)",
        "reservation_id": 4294,
        "user_name": "전세현2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 523,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "19",
        "start_mi": "00",
        "end_hh": "19",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T19:20",
        "end": "2024-05-27T19:40",
        "title": "이동의(현우)",
        "reservation_id": 4295,
        "user_name": "이동의(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 592,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "19",
        "start_mi": "20",
        "end_hh": "19",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T19:40",
        "end": "2024-05-27T20:00",
        "title": "이신애(현우)",
        "reservation_id": 4296,
        "user_name": "이신애(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 522,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "19",
        "start_mi": "40",
        "end_hh": "20",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T20:00",
        "end": "2024-05-27T20:20",
        "title": "이동의(현우)",
        "reservation_id": 4297,
        "user_name": "이동의(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 592,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "20",
        "start_mi": "00",
        "end_hh": "20",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T21:00",
        "end": "2024-05-27T21:20",
        "title": "이도하(현우)",
        "reservation_id": 4299,
        "user_name": "이도하(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 656,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "21",
        "start_mi": "00",
        "end_hh": "21",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T20:40",
        "end": "2024-05-27T21:00",
        "title": "김여진(현우)",
        "reservation_id": 4300,
        "user_name": "김여진(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 616,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "20",
        "start_mi": "40",
        "end_hh": "21",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T21:20",
        "end": "2024-05-27T21:40",
        "title": "진홍구(현우)",
        "reservation_id": 4301,
        "user_name": "진홍구(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 536,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-27",
        "start_hh": "21",
        "start_mi": "20",
        "end_hh": "21",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-27T21:40",
        "end": "2024-05-27T22:00",
        "title": "윤창희2(현우)",
        "reservation_id": 4302,
        "user_name": "윤창희2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 605,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-27",
        "start_hh": "21",
        "start_mi": "40",
        "end_hh": "22",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T11:20",
        "end": "2024-05-28T11:40",
        "title": "유영창(현우)",
        "reservation_id": 4351,
        "user_name": "유영창(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 515,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "11",
        "start_mi": "20",
        "end_hh": "11",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T16:20",
        "end": "2024-05-28T16:40",
        "title": "송영은(현우)",
        "reservation_id": 4367,
        "user_name": "송영은(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 493,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "16",
        "start_mi": "20",
        "end_hh": "16",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T19:40",
        "end": "2024-05-29T20:00",
        "title": "이신애(현우)",
        "reservation_id": 4352,
        "user_name": "이신애(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 522,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "19",
        "start_mi": "40",
        "end_hh": "20",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T06:20",
        "end": "2024-05-28T06:40",
        "title": "권민예(현우)",
        "reservation_id": 4353,
        "user_name": "권민예(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 573,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "06",
        "start_mi": "20",
        "end_hh": "06",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T06:40",
        "end": "2024-05-28T07:00",
        "title": "구유성(현우)",
        "reservation_id": 4354,
        "user_name": "구유성(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 575,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "06",
        "start_mi": "40",
        "end_hh": "07",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T07:00",
        "end": "2024-05-28T07:20",
        "title": "이형창(현우)",
        "reservation_id": 4355,
        "user_name": "이형창(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 606,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "07",
        "start_mi": "00",
        "end_hh": "07",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T08:20",
        "end": "2024-05-28T08:40",
        "title": "강지훈(현우)",
        "reservation_id": 4356,
        "user_name": "강지훈(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 629,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "08",
        "start_mi": "20",
        "end_hh": "08",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T08:40",
        "end": "2024-05-28T09:00",
        "title": "박종원(현우)",
        "reservation_id": 4357,
        "user_name": "박종원(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 433,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "08",
        "start_mi": "40",
        "end_hh": "09",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T09:00",
        "end": "2024-05-28T09:20",
        "title": "배선희(현우)",
        "reservation_id": 4358,
        "user_name": "배선희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 649,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "09",
        "start_mi": "00",
        "end_hh": "09",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T09:20",
        "end": "2024-05-28T09:40",
        "title": "최다희(현우)",
        "reservation_id": 4359,
        "user_name": "최다희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 630,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "09",
        "start_mi": "20",
        "end_hh": "09",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T09:40",
        "end": "2024-05-28T10:00",
        "title": "최다희(현우)",
        "reservation_id": 4360,
        "user_name": "최다희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 630,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "09",
        "start_mi": "40",
        "end_hh": "10",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T10:00",
        "end": "2024-05-28T10:20",
        "title": "김지수(현우)",
        "reservation_id": 4361,
        "user_name": "김지수(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 608,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "10",
        "start_mi": "00",
        "end_hh": "10",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T10:20",
        "end": "2024-05-28T10:40",
        "title": "박목은(현우)",
        "reservation_id": 4362,
        "user_name": "박목은(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 607,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "10",
        "start_mi": "20",
        "end_hh": "10",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T10:40",
        "end": "2024-05-28T11:00",
        "title": "최준현(현우)",
        "reservation_id": 4363,
        "user_name": "최준현(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 588,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-28",
        "start_hh": "10",
        "start_mi": "40",
        "end_hh": "11",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T11:00",
        "end": "2024-05-28T11:20",
        "title": "최정운2(현우)",
        "reservation_id": 4364,
        "user_name": "최정운2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 560,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "11",
        "start_mi": "00",
        "end_hh": "11",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T15:00",
        "end": "2024-05-28T15:20",
        "title": "성진후(현우)",
        "reservation_id": 4365,
        "user_name": "성진후(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 610,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "15",
        "start_mi": "00",
        "end_hh": "15",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T16:00",
        "end": "2024-05-28T16:20",
        "title": "이승민(현우)",
        "reservation_id": 4366,
        "user_name": "이승민(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 485,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "16",
        "start_mi": "00",
        "end_hh": "16",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T16:40",
        "end": "2024-05-28T17:00",
        "title": "황선진(현우)",
        "reservation_id": 4368,
        "user_name": "황선진(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 574,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "16",
        "start_mi": "40",
        "end_hh": "17",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T17:00",
        "end": "2024-05-28T17:20",
        "title": "황선진(현우)",
        "reservation_id": 4369,
        "user_name": "황선진(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 574,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "17",
        "start_mi": "00",
        "end_hh": "17",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T18:00",
        "end": "2024-05-28T18:20",
        "title": "남규리(현우)",
        "reservation_id": 4370,
        "user_name": "남규리(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 530,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "18",
        "start_mi": "00",
        "end_hh": "18",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T19:20",
        "end": "2024-05-28T19:40",
        "title": "윤창희2(현우)",
        "reservation_id": 4372,
        "user_name": "윤창희2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 605,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-28",
        "start_hh": "19",
        "start_mi": "20",
        "end_hh": "19",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T19:40",
        "end": "2024-05-28T20:00",
        "title": "장성민(현우)",
        "reservation_id": 4373,
        "user_name": "장성민(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 537,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-28",
        "start_hh": "19",
        "start_mi": "40",
        "end_hh": "20",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T20:00",
        "end": "2024-05-28T20:20",
        "title": "김예지(현우)",
        "reservation_id": 4374,
        "user_name": "김예지(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 580,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "20",
        "start_mi": "00",
        "end_hh": "20",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T20:40",
        "end": "2024-05-28T21:00",
        "title": "백승훈(현우)",
        "reservation_id": 4376,
        "user_name": "백승훈(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 582,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "20",
        "start_mi": "40",
        "end_hh": "21",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T21:00",
        "end": "2024-05-28T21:20",
        "title": "이주영(현우)",
        "reservation_id": 4377,
        "user_name": "이주영(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 543,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "21",
        "start_mi": "00",
        "end_hh": "21",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T21:20",
        "end": "2024-05-28T21:40",
        "title": "이정민(현우)",
        "reservation_id": 4378,
        "user_name": "이정민(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 442,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-28",
        "start_hh": "21",
        "start_mi": "20",
        "end_hh": "21",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T21:40",
        "end": "2024-05-28T22:00",
        "title": "전은지(현우)",
        "reservation_id": 4379,
        "user_name": "전은지(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 577,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-28",
        "start_hh": "21",
        "start_mi": "40",
        "end_hh": "22",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T19:00",
        "end": "2024-05-28T19:20",
        "title": "추수진(현우)",
        "reservation_id": 4371,
        "user_name": "추수진(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 565,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-28",
        "start_hh": "19",
        "start_mi": "00",
        "end_hh": "19",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-28T20:20",
        "end": "2024-05-28T20:40",
        "title": "이현수(현우)",
        "reservation_id": 4375,
        "user_name": "이현수(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 579,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-28",
        "start_hh": "20",
        "start_mi": "20",
        "end_hh": "20",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T06:20",
        "end": "2024-05-29T06:40",
        "title": "이경선(현우)",
        "reservation_id": 4391,
        "user_name": "이경선(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 535,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "06",
        "start_mi": "20",
        "end_hh": "06",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T07:00",
        "end": "2024-05-29T07:20",
        "title": "최종현2(현우)",
        "reservation_id": 4392,
        "user_name": "최종현2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 502,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "07",
        "start_mi": "00",
        "end_hh": "07",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T08:20",
        "end": "2024-05-29T08:40",
        "title": "유영창(현우)",
        "reservation_id": 4393,
        "user_name": "유영창(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 675,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "08",
        "start_mi": "20",
        "end_hh": "08",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T08:40",
        "end": "2024-05-29T09:00",
        "title": "조정일(현우)",
        "reservation_id": 4394,
        "user_name": "조정일(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 663,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "08",
        "start_mi": "40",
        "end_hh": "09",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T10:00",
        "end": "2024-05-29T10:20",
        "title": "김권혁(현우)",
        "reservation_id": 4395,
        "user_name": "김권혁(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 558,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-29",
        "start_hh": "10",
        "start_mi": "00",
        "end_hh": "10",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T10:20",
        "end": "2024-05-29T10:40",
        "title": "임예은(현우)",
        "reservation_id": 4396,
        "user_name": "임예은(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 557,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-29",
        "start_hh": "10",
        "start_mi": "20",
        "end_hh": "10",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T10:40",
        "end": "2024-05-29T11:00",
        "title": "이상일2(현우)",
        "reservation_id": 4397,
        "user_name": "이상일2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 667,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "10",
        "start_mi": "40",
        "end_hh": "11",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T11:00",
        "end": "2024-05-29T11:20",
        "title": "박건민(현우)",
        "reservation_id": 4398,
        "user_name": "박건민(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 620,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "11",
        "start_mi": "00",
        "end_hh": "11",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T11:20",
        "end": "2024-05-29T11:40",
        "title": "오준영(현우)",
        "reservation_id": 4399,
        "user_name": "오준영(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 651,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "11",
        "start_mi": "20",
        "end_hh": "11",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T11:40",
        "end": "2024-05-29T12:00",
        "title": "김정휘(현우)",
        "reservation_id": 4400,
        "user_name": "김정휘(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 554,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "11",
        "start_mi": "40",
        "end_hh": "12",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T15:00",
        "end": "2024-05-29T15:20",
        "title": "이대건(현우)",
        "reservation_id": 4401,
        "user_name": "이대건(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 609,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "15",
        "start_mi": "00",
        "end_hh": "15",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T17:00",
        "end": "2024-05-29T17:20",
        "title": "이정원(현우)",
        "reservation_id": 4402,
        "user_name": "이정원(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 640,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "17",
        "start_mi": "00",
        "end_hh": "17",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T17:20",
        "end": "2024-05-29T17:40",
        "title": "추교범(현우)",
        "reservation_id": 4403,
        "user_name": "추교범(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 623,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "17",
        "start_mi": "20",
        "end_hh": "17",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T18:00",
        "end": "2024-05-29T18:20",
        "title": "오동민(현우)",
        "reservation_id": 4404,
        "user_name": "오동민(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 641,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "18",
        "start_mi": "00",
        "end_hh": "18",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T18:40",
        "end": "2024-05-29T19:00",
        "title": "정영훈(현우)",
        "reservation_id": 4405,
        "user_name": "정영훈(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 460,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "18",
        "start_mi": "40",
        "end_hh": "19",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T19:00",
        "end": "2024-05-29T19:20",
        "title": "이재갑2(현우)",
        "reservation_id": 4406,
        "user_name": "이재갑2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 655,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-29",
        "start_hh": "19",
        "start_mi": "00",
        "end_hh": "19",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T19:20",
        "end": "2024-05-29T19:40",
        "title": "전세현2(현우)",
        "reservation_id": 4407,
        "user_name": "전세현2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 523,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "19",
        "start_mi": "20",
        "end_hh": "19",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T20:00",
        "end": "2024-05-29T20:20",
        "title": "이혜리2(현우)",
        "reservation_id": 4408,
        "user_name": "이혜리2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 555,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "20",
        "start_mi": "00",
        "end_hh": "20",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T20:20",
        "end": "2024-05-29T20:40",
        "title": "김태희2(현우)",
        "reservation_id": 4409,
        "user_name": "김태희2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 628,
        "membership_name": "주말 주1회",
        "reservation_color": "#009dff",
        "reservation_dt": "2024-05-29",
        "start_hh": "20",
        "start_mi": "20",
        "end_hh": "20",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T20:40",
        "end": "2024-05-29T21:00",
        "title": "김호연(현우)",
        "reservation_id": 4410,
        "user_name": "김호연(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 542,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "20",
        "start_mi": "40",
        "end_hh": "21",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T21:00",
        "end": "2024-05-29T21:20",
        "title": "김호연(현우)",
        "reservation_id": 4411,
        "user_name": "김호연(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 542,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "21",
        "start_mi": "00",
        "end_hh": "21",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T21:20",
        "end": "2024-05-29T21:40",
        "title": "이도하(현우)",
        "reservation_id": 4412,
        "user_name": "이도하(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 656,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-29",
        "start_hh": "21",
        "start_mi": "20",
        "end_hh": "21",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-29T21:40",
        "end": "2024-05-29T22:00",
        "title": "이서희(현우)",
        "reservation_id": 4413,
        "user_name": "이서희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 650,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-29",
        "start_hh": "21",
        "start_mi": "40",
        "end_hh": "22",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T06:40",
        "end": "2024-05-30T07:00",
        "title": "박동희(현우)",
        "reservation_id": 4428,
        "user_name": "박동희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 618,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "06",
        "start_mi": "40",
        "end_hh": "07",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T07:00",
        "end": "2024-05-30T07:20",
        "title": "이형창(현우)",
        "reservation_id": 4429,
        "user_name": "이형창(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 606,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "07",
        "start_mi": "00",
        "end_hh": "07",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T08:20",
        "end": "2024-05-30T08:40",
        "title": "강지훈(현우)",
        "reservation_id": 4430,
        "user_name": "강지훈(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 629,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "08",
        "start_mi": "20",
        "end_hh": "08",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T08:40",
        "end": "2024-05-30T09:00",
        "title": "박종원(현우)",
        "reservation_id": 4431,
        "user_name": "박종원(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 433,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "08",
        "start_mi": "40",
        "end_hh": "09",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T09:20",
        "end": "2024-05-30T09:40",
        "title": "최다희(현우)",
        "reservation_id": 4432,
        "user_name": "최다희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 630,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "09",
        "start_mi": "20",
        "end_hh": "09",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T09:40",
        "end": "2024-05-30T10:00",
        "title": "박목은(현우)",
        "reservation_id": 4433,
        "user_name": "박목은(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 607,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "09",
        "start_mi": "40",
        "end_hh": "10",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T10:00",
        "end": "2024-05-30T10:20",
        "title": "김지수(현우)",
        "reservation_id": 4434,
        "user_name": "김지수(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 608,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "10",
        "start_mi": "00",
        "end_hh": "10",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T11:20",
        "end": "2024-05-30T11:40",
        "title": "마수오(현우)",
        "reservation_id": 4435,
        "user_name": "마수오(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 589,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "11",
        "start_mi": "20",
        "end_hh": "11",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T11:40",
        "end": "2024-05-30T12:00",
        "title": "마수오(현우)",
        "reservation_id": 4436,
        "user_name": "마수오(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 589,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "11",
        "start_mi": "40",
        "end_hh": "12",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T15:00",
        "end": "2024-05-30T15:20",
        "title": "성진후(현우)",
        "reservation_id": 4446,
        "user_name": "성진후(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 610,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "15",
        "start_mi": "00",
        "end_hh": "15",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T16:00",
        "end": "2024-05-30T16:20",
        "title": "남기용(정록)",
        "reservation_id": 4447,
        "user_name": "남기용(정록)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 685,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "16",
        "start_mi": "00",
        "end_hh": "16",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T16:20",
        "end": "2024-05-30T16:40",
        "title": "송영은(현우)",
        "reservation_id": 4448,
        "user_name": "송영은(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 493,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "16",
        "start_mi": "20",
        "end_hh": "16",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T17:00",
        "end": "2024-05-30T17:20",
        "title": "박다유2(현우)",
        "reservation_id": 4449,
        "user_name": "박다유2(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 590,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-30",
        "start_hh": "17",
        "start_mi": "00",
        "end_hh": "17",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T17:20",
        "end": "2024-05-30T17:40",
        "title": "장안길(현우)",
        "reservation_id": 4450,
        "user_name": "장안길(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 647,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "17",
        "start_mi": "20",
        "end_hh": "17",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T17:40",
        "end": "2024-05-30T18:00",
        "title": "박수정(현우)",
        "reservation_id": 4451,
        "user_name": "박수정(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 648,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "17",
        "start_mi": "40",
        "end_hh": "18",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T18:00",
        "end": "2024-05-30T18:20",
        "title": "남규리(현우)",
        "reservation_id": 4452,
        "user_name": "남규리(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 530,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "18",
        "start_mi": "00",
        "end_hh": "18",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T18:20",
        "end": "2024-05-30T18:40",
        "title": "배선희(현우)",
        "reservation_id": 4453,
        "user_name": "배선희(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 649,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "18",
        "start_mi": "20",
        "end_hh": "18",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T18:40",
        "end": "2024-05-30T19:00",
        "title": "박채린(현우)",
        "reservation_id": 4454,
        "user_name": "박채린(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 591,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "18",
        "start_mi": "40",
        "end_hh": "19",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T19:20",
        "end": "2024-05-30T19:40",
        "title": "진홍구(현우)",
        "reservation_id": 4455,
        "user_name": "진홍구(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 536,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "19",
        "start_mi": "20",
        "end_hh": "19",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T19:40",
        "end": "2024-05-30T20:00",
        "title": "김경숙(현우)",
        "reservation_id": 4456,
        "user_name": "김경숙(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 529,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "19",
        "start_mi": "40",
        "end_hh": "20",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T20:00",
        "end": "2024-05-30T20:20",
        "title": "김예지(현우)",
        "reservation_id": 4457,
        "user_name": "김예지(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 580,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "20",
        "start_mi": "00",
        "end_hh": "20",
        "end_mi": "20",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T20:20",
        "end": "2024-05-30T20:40",
        "title": "장여정(현우)",
        "reservation_id": 4458,
        "user_name": "장여정(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 595,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "20",
        "start_mi": "20",
        "end_hh": "20",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T20:40",
        "end": "2024-05-30T21:00",
        "title": "김여진(현우)",
        "reservation_id": 4459,
        "user_name": "김여진(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 616,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "20",
        "start_mi": "40",
        "end_hh": "21",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T21:20",
        "end": "2024-05-30T21:40",
        "title": "이정민(현우)",
        "reservation_id": 4460,
        "user_name": "이정민(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 442,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "21",
        "start_mi": "20",
        "end_hh": "21",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T21:40",
        "end": "2024-05-30T22:00",
        "title": "이현기(현우)",
        "reservation_id": 4461,
        "user_name": "이현기(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 617,
        "membership_name": "평일 주1회",
        "reservation_color": "#51c3d2",
        "reservation_dt": "2024-05-30",
        "start_hh": "21",
        "start_mi": "40",
        "end_hh": "22",
        "end_mi": "00",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    },
    {
        "start": "2024-05-30T06:20",
        "end": "2024-05-30T06:40",
        "title": "권민예(현우)",
        "reservation_id": 4427,
        "user_name": "권민예(현우)",
        "memo": "",
        "class_id": "a1",
        "class_name": "현우",
        "user_membership_id": 573,
        "membership_name": "평일 주2회",
        "reservation_color": "#d4f000",
        "reservation_dt": "2024-05-30",
        "start_hh": "06",
        "start_mi": "20",
        "end_hh": "06",
        "end_mi": "40",
        "status_atdc": "Y",
        "status_atdc_text": "출석"
    }
]';